#!/bin/sh

set -e

CARD=/mnt
SWU=${CARD}/venus.swu
DATA=${CARD}/data.tar

msg() {
    echo "$@"
    echo "$@" >/dev/tty0
}

pause() {
    while :; do sleep 10; done
}

error() {
    test -n "$*" && msg "$*"
    msg "Error installing software"
    pause
}

trap error EXIT

mount -t proc none /proc
mount -t sysfs none /sys
# manually mount devtmpfs if not done by linux
if ! `mount | grep -q " on /dev "`; then
	mount -t devtmpfs none /dev
fi

mkdir -p /run/lock

msg "Searching for update image..."

for d in sda1 mmcblk0p1 sda mmcblk0; do
    if mount /dev/$d ${CARD}; then
        if [ -f ${SWU} ]; then
            DEV=$d
            break
        fi
        umount ${CARD}
    fi
done

if [ -n "${DEV}" ]; then
    msg "Update image found on ${DEV}"
else
    error "Update image not found"
fi

# opkg based install have the data partition at a different location, which is
# passed as mtd13 by the u-boot script. If it mounts we are upgrading to an
# swupdate enabled deployment and data needs to preserved, since the partition
# will be formatted.
if ubiattach -m 13 -d 1; then
    msg "Saving data partition..."
    mkdir -p /data
    mount -r -t ubifs /dev/ubi1_0 /data
    echo log >/tmp/exclude
    tar c -f ${DATA} -C /data -X /tmp/exclude .
    umount /data
    ubidetach -m 13
fi

# NOTE: this formats above data partition as well...
# XXX: should this always be done, or only when converting?
if ! ubiattach -m 12; then
    msg "Formatting UBI partition..."
    ubiformat --yes /dev/mtd12
    ubiattach -m 12
    ubimkvol /dev/ubi0 -N rootfs1 -s 200MiB
    ubimkvol /dev/ubi0 -N rootfs2 -s 200MiB
    ubimkvol /dev/ubi0 -N data -s 32MiB

    msg "Creating /data/venus/upgrader-version..."
    mkdir -p /data
    mount -t ubifs ubi0:data /data
    mkdir -p /data/venus
    cp /opt/color-control/version /data/venus/upgrader-version
    umount /data
fi

# -b '0..!12..13' tells swupdate ubi volume is on mtd 12 (all others are blacklisted)
set -- -b "0 1 2 3 4 5 6 7 8 9 10 11 13" -i ${SWU}

msg "Installing rootfs1..."
swupdate "$@" -e "stable,copy1"

msg "Installing rootfs2..."
swupdate "$@" -e "stable,copy2"

msg "updating boot instructions..."
fw_setenv -s /usr/share/u-boot/u-boot.env

if [ -e ${DATA} ]; then
    msg "Restoring data partition..."
    mount -t ubifs ubi0:data /data
    tar x -f ${DATA} -C /data
    umount /data
    rm -f ${DATA}

    msg "installing redundant primary loaders..."
    swupdate "$@" -e "stable,backup-mlo"
fi

ubidetach -m 12
umount ${CARD}

msg "Installation complete"
msg "Remove SD/USB medium and reset system"
pause
