#!/bin/sh

set -e

CARD=/mnt/card
SWU=${CARD}/venus.swu
DATA=${CARD}/data.tar

msg() {
    echo "$@"
    echo "$@" >/dev/tty0
}

pause() {
    while :; do sleep 10; done
}

error() {
    test -n "$*" && msg "$*"
    msg "Error installing software"
    pause
}

trap error EXIT

mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys

modprobe fbcon

msg "Searching for update image..."

for d in sda1 mmcblk0p1; do
    if mount /dev/$d ${CARD}; then
        if [ -f ${SWU} ]; then
            DEV=$d
            break
        fi
        umount ${CARD}
    fi
done

if [ -n "${DEV}" ]; then
    msg "Update image found on ${DEV}"
else
    error "Update image not found"
fi

# opkg based install have the data partition at a different location, which is
# passed as mtd13 by the u-boot script. If it mounts we are upgrading to an
# swupdate enabled deployment and data needs to preserved, since the partition
# will be formatted.
if ubiattach -m 13 -d 1; then
    msg "Saving data partition..."
    mkdir -p /data
    mount -r -t ubifs /dev/ubi1_0 /data
    echo log >/tmp/exclude
    tar c -f ${DATA} -C /data -X /tmp/exclude .
    umount /data
    ubidetach -m 13
fi

# NOTE: this formats above data parition as well...
# XXX: should this always be done, or only when converting?
if ! ubiattach -m 12; then
    msg "Formatting UBI partition..."
    ubiformat /dev/mtd12
    ubiattach -m 12
    ubimkvol /dev/ubi0 -N rootfs1 -s 200MiB
    ubimkvol /dev/ubi0 -N rootfs2 -s 200MiB
    ubimkvol /dev/ubi0 -N data -s 32MiB
fi

# NOTE: while the mtd partitions number differ for the bpp3/ccgx, their location
# is the same. There is no valid reason this should fail.
case $(fw_printenv -n mtdparts 2>&1) in
    *Bad\ CRC*)  uboot=none ;;  # invalid environment
    *data*)      uboot=old  ;;  # pre-swupdate software
esac

if [ "$uboot" = none ]; then
    msg "The boot loader seems corrupt, please contact victronenergy..."
    pause
fi

if fw_printenv upd_mode >/dev/null 2>&1; then
    uboot=old                   # pre-swupdate u-boot with new software
fi

# XXX: why?
#msg "Erasing u-boot environment..."
#flash_erase /dev/mtd5 0 0
#flash_erase /dev/mtd6 0 0

# -b '0..!12..13' tells swupdate ubi volume is on mtd 12 (all others are blacklisted)
set -- -b "0 1 2 3 4 5 6 7 8 9 10 11 13" -i ${SWU}

msg "Installing rootfs1..."
swupdate "$@" -e "stable,copy1"

msg "Installing rootfs2..."
swupdate "$@" -e "stable,copy2"

if [ "$uboot" = old ]; then
    preboot=$(fw_printenv -n preboot)
    # CHECKME: there are more preboot script for ve-direct iirc
    fw_setenv -s - <<-EOF
	preboot nand read 8fe00000 splash 7f800; $preboot
	upd_mode 1
	EOF
fi

if [ -e ${DATA} ]; then
    msg "Restoring data partition..."
    mount -t ubifs ubi0:data /data
    tar x -f ${DATA} -C /data
    umount /data
    rm -f ${DATA}

    #XXX, program ml02,3,4
fi

ubidetach -m 12
umount ${CARD}

msg "Installation complete"
msg "Remove SD/USB medium and reset system"
pause
