#! /bin/sh

case $(board-compat) in
	victronenergy,cerbo-gx*|victronenergy,nucleo-gx)
		leds_off="status-green=none status-orange=blink-slow"
		leds_on="status-green=blink-slow status-orange=none"
		;;
	sancloud,am335x-boneenhanced|unipoin,gridless-octo)
		leds_off="vecape:green:ve0=blink-slow"
		leds_on="vecape:green:ve0=blink-fast"
		;;
esac

set_leds() {
	for led; do
		name=${led%=*}
		trig=${led#*=}

		# Write LED settings to temporary files, venus-platform watches
		# these files and copies the contents to /sys/class/leds/../
		# depending on whether the LEDs are enabled.
		mkdir -p /run/leds/$name/
		echo $trig >/run/leds/$name/trigger
	done
}

gen_config() {
	serial=$(cat /data/venus/serial-number)
	# output of dbus-send contains 2 lines of which one looks like:    variant   string  "......"
	# The grep command will return the line with the variant string, and the awk command will remove
	# the "    variant     string  " and the opening en closing quotes, keeping quotes that are part of the psk.
	# When the regex does not match 2 times (once for "   variant   string  "" and once for the closing ") or the result
	# is shorter than 8 characters, it will return nothing.
	psk=$(dbus-send --system --print-reply --dest=com.victronenergy.settings /Settings/Services/AccessPointPassword com.victronenergy.BusItem.GetValue 2>/dev/null | grep variant | awk '{ if (gsub(/^\s+variant\s+string\s+"|"$/, "", $0) == 2 && length($0) >= 8) print$0 }')
	if [ "$psk" = "" ]; then
		# If the result is empty, we will use the psk from /data/venus/wpa-psk
		psk=$(cat /data/venus/wpa-psk)
	fi

	apd_id=""
	bad_id=$(bad-unique-id)
	if [ "$bad_id" != "" ]; then
		# If there is a bad-unique-id, use that, since it is printed on the device and
		# included in the QR-code.
		apd_id="$bad_id"

		# But not for early Cerbo's, while they do have bad-unique-id's, they did
		# use the unique-id for the hostapd. That behaviour shouldn't suddenly change
		# after years.
		if [ "$(product-id)" = "C00A" ]; then
			installer_version="$(sed -n '3p' /data/venus/installer-version 2>/dev/null)"
			if [ ${installer_version:-0} -lt 20200706000000 ]; then
				apd_id=""
			fi
		fi
	fi

	if [ "$apd_id" = "" ]; then
		apd_id=$(cat /data/venus/unique-id)
	fi

	apd_id=${apd_id: -3}

	test -n "$serial" -a -n "$psk" -a -n "$apd_id" || return 1

	echo "Creating /run/hostapd.conf"
	cat /etc/hostapd.conf - <<-EOF >/run/hostapd.conf || return 1
	ssid=venus-${serial}-${apd_id}
	wpa_passphrase=${psk}
EOF
}

stop() {
	svc -d .
	exit 1
}

finish() {
	test -n "$pid" && kill $pid
	set_leds $leds_off
}

# make sure interface exists
ip link show ap0 >/dev/null 2>&1 || stop

gen_config || stop

rfkill unblock wifi
set_leds $leds_on

trap finish EXIT

/usr/sbin/hostapd /run/hostapd.conf &
pid=$!
wait
