#! /bin/sh

case $(board-compat) in
	victronenergy,cerbo-gx)
		leds_off="status-green=none status-orange=blink-slow"
		leds_on="status-green=blink-slow status-orange=none"
		;;
	sancloud,am335x-boneenhanced|unipoin,gridless-octo)
		leds_off="vecape:green:ve0=blink-slow"
		leds_on="vecape:green:ve0=blink-fast"
		;;
esac

set_leds() {
	for led; do
		name=${led%=*}
		trig=${led#*=}
		echo $trig >/sys/class/leds/$name/trigger
	done
}

gen_config() {
	test -e /run/hostapd.conf && return 0

	serial=$(cat /data/venus/serial-number)
	psk=$(cat /data/venus/wpa-psk)
	vrm=$(sed 's/.*\(...\)$/\1/' /data/venus/unique-id)

	test -n "$serial" -a -n "$psk" -a -n "$vrm" || return 1

	echo "Creating /run/hostapd.conf"
	cat /etc/hostapd.conf - <<-EOF >/run/hostapd.conf || return 1
	ssid=venus-${serial}-${vrm}
	wpa_passphrase=${psk}
EOF
}

stop() {
	svc -d .
	exit 1
}

finish() {
	test -n "$pid" && kill $pid
	set_leds $leds_off
}

# make sure interface exists
iw dev ap0 info >/dev/null 2>&1 || stop

gen_config || stop

rfkill unblock wifi
set_leds $leds_on

trap finish EXIT

/usr/sbin/hostapd /run/hostapd.conf &
pid=$!
wait
