#!/bin/sh
DAEMON=/usr/bin/dnsmasq
NAME=$(basename $0)
NAME=${NAME#[SK]??}
DESC="DNS forwarder and DHCP server"
PIDFILE=/var/run/$NAME.pid
ARGS="-x $PIDFILE -C /etc/$NAME.conf"

test -f $DAEMON || exit 0

set -e

case "$1" in
    start)
        echo -n "starting $DESC: $NAME... "
        start-stop-daemon -S -p $PIDFILE -x $DAEMON -- $ARGS
        echo "done."
        ;;
    stop)
        echo -n "stopping $DESC: $NAME... "
        start-stop-daemon -K -p $PIDFILE -x $DAEMON
        echo "done."
        ;;
    status)
        echo -n "dnsmasq "
        if start-stop-daemon -q -K -t -p $PIDFILE -x $DAEMON; then
            PID=$(cat $PIDFILE)
            echo "($PID) is running"
        else
            echo "is not running"
            exit 1
        fi
        ;;
    restart)
        echo "restarting $DESC: $NAME... "
        $0 stop
        $0 start
        echo "done."
        ;;
    reload)
        echo -n "reloading $DESC: $NAME... "
        kill -HUP $(cat $PIDFILE)
        echo "done."
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart|reload}"
        exit 1
        ;;
esac

exit 0
