#! /bin/sh

event=$1
dev=$2
addr=$3

case "$event" in
    BIND)
        ip addr add ${addr}/16 scope link dev ${dev}
        ;;

    CONFLICT|UNBIND|STOP)
        ip addr del ${addr}/16 scope link dev ${dev}
        ;;

    *)
        echo "Unknown event $event" >&2
        exit 1
        ;;
esac
