#!/bin/sh

interfaces=$(ip -o link show type can | awk -F': ' '{print $2}' | tr '\n' ',' | sed -e 's/,$//')
if [ "$interfaces" = "" ]; then
	svc -d .
	exit 1
fi

# If ethernet is not connected, binding will fail. Lets not hog the
# cpu and simply add a delay here.
if ! socketcand -i $interfaces -v; then
	sleep 60
fi
