#! /bin/sh

set -e

PART=$1
: ${SERIAL:=${HID_UNIQ}}
DIR=/run/io-ext/$SERIAL
CONF=$DIR/pins.conf

R0_PINS="relay_1 2:in 5:set 6:res"
R1_PINS="relay_2 1:in 3:set 4:res"
SSR_PINS="ssr_3 0:"

G0_PINS="9 0:1 1:2 2:3 3:4"
G1_PINS="8 11:5 12:6 13:7 14:8"
PWM_EN_PIN=15

setup_group() (
    gpio_base=$1
    dirpin=$2
    shift 2

    dirgpio=$((gpio_base + dirpin))
    echo $dirgpio >/sys/class/gpio/export
    dir=/sys/class/gpio/gpio$dirgpio
    echo in >$dir/direction
    dirval=$(cat $dir/value)

    if [ $dirval = 0 ]; then
        direction=low
        label=output
    else
        direction=in
        label=input
    fi

    for pin; do
        p=${pin%:*}
        n=${pin#*:}
        gpio=$((gpio_base + p))
        echo $gpio >/sys/class/gpio/export
        echo $direction >/sys/class/gpio/gpio$gpio/direction
        link=$DIR/${label}_$n
        ln -s /sys/class/gpio/gpio$gpio $link
        echo "$label	$link $n" >>$CONF
    done
)

setup_relay() {
    gpio_base=$1
    label=$2
    shift 2

    for pin; do
        p=${pin%:*}
        n=${pin#*:}
        gpio=$((gpio_base + p))

        case $n in
            in) direction=in  ;;
            *)  direction=low ;;
        esac

        echo $gpio >/sys/class/gpio/export
        echo $direction >/sys/class/gpio/gpio$gpio/direction
        link=$DIR/$label${n:+_$n}
        ln -s /sys/class/gpio/gpio$gpio $link
    done

    link=$DIR/$label
    n=${label#*_}
    echo "relay	$link $n" >>$CONF
}

setup_dio() {
    dev=$(realpath /sys/$DEVPATH/../../../..)
    gpio_base=$(cat $dev/gpio/*/base)
    gpio_base_i2c=$(cat $dev/i2c-*/*-0020/gpio/*/base)

    setup_group $gpio_base_i2c $G0_PINS
    setup_group $gpio_base_i2c $G1_PINS
    setup_relay $gpio_base $R0_PINS
    setup_relay $gpio_base $R1_PINS
    setup_relay $gpio_base $SSR_PINS

    # PWN enable pin
    gpio=$((gpio_base_i2c + PWM_EN_PIN))
    echo $gpio >/sys/class/gpio/export
    echo out >/sys/class/gpio/gpio$gpio/direction
    # Enable PWM by default
    echo 0 >/sys/class/gpio/gpio$gpio/value
}

setup_pwm() {
    for led in $(ls /sys/$DEVPATH/leds); do
        num=${led##*[!0-9]}
        link=$DIR/pwm$num
        ln -s /sys/class/leds/$led/brightness $link
        echo "pwm	$link $((num+1))" >>$CONF
    done
}

svc_update() {
    case $1 in
        add) args="" ;;
        del) args="-r" ;;
    esac

    /opt/victronenergy/venus-platform/svectl $args -s dbus-switch -D SERIAL=$SERIAL
}

case $ACTION in
    add)
        mkdir -p $DIR
        exec {fd}<$DIR
        flock $fd

        if [ ! -e $CONF ]; then
            echo "tag	$SERIAL" >$CONF
        fi

        case $PART in
            gpio) setup_dio ;;
            pwm)  setup_pwm ;;
        esac

        # Both parts have been configured, (re)start services
        if [ -e $DIR/pwm0 -a -e $DIR/relay_1_in ]; then
                svc_update add
                restart_digitalinputs=1
        fi

        ;;
    remove)
        if [ -e "$DIR" ]; then
            rm -rf "$DIR"
            svc_update del
            restart_digitalinputs=1
        fi
        ;;
esac

if [ "$restart_digitalinputs" = 1 ]; then
    svc -t /service/dbus-digitalinputs
    svc -u /service/dbus-digitalinputs
fi
