#!/bin/sh
#
# Although FlashMQ use this key nowadays, it is still called mosquitto.

keydir=/data/keys
cert=$keydir/mosquitto.crt
key=$keydir/mosquitto.key

mkdir -p $keydir
# note: older devices have 700 as permission, always change it so
# the flashmq user can access it.
chmod 755 /data/keys

tempconf=$(mktemp)

cat > "$tempconf" << EOF
listen {
  port 50021
  fullchain $cert
  privkey $key
}
EOF

# FlashMQ actually creates an SSL context with key and cert, so it will detect
# it if they are invalid.
if ! nohup /usr/bin/flashmq --test-config --config-file "$tempconf" >/dev/null 2>/dev/null ||
   ! openssl verify -CAfile $cert $cert ||
   ! openssl x509 -noout -checkend 31536000 -in $cert; then
    openssl req -subj /CN=venus.local -newkey rsa:2048 -nodes \
            -keyout $key -x509 -days 36524 -out $cert
fi

rm "$tempconf"

chmod 400 $key
chown flashmq $key

exec softlimit -d 150000000 -s 10000000 -a 150000000 setuidgid flashmq /usr/bin/flashmq
