#!/bin/sh

N=${1:-1}

# return the Nth dtb compatible string. Since different products
# can have the same board, use this for board configuration.
cat /sys/firmware/devicetree/base/compatible | tr '\0' '\n' | sed -n "${N}p"
