#!/bin/sh

case $(product-name) in
"Color Control GX")
	echo C001
	;;
"Venus GX")
	echo C002
	;;
"Octo GX")
	echo C006
	;;
"EasySolar-II")
	echo C007
	;;
"MultiPlus-II")
	echo C008
	;;
"Maxi GX")
	echo C009
	;;
*)
	echo C003
esac

