#!/bin/sh

if [ "$1" = "-h" ]; then
	echo "usage: $0"
	echo
	echo "After April 2024 all product are shipped with the BlueTooth PIN as"
	echo "default password, this wasn't the case before that."
	echo
	echo "Returns if the product left the factory with the PIN as password,"
	echo "which can e.g. be used to restore a product to its default factory state."
	echo
	echo "example:"
	echo
	echo "  if ve-is-password-set-by-default; then"
	echo "     There was a unique password set by default and it should be restored for factory default"
	echo "  else:"
	echo "     The product left the factory without a default unique password, and the user is"
	echo "     expected to set one first if a password is required or disable the password check."
fi

installer_version="$(sed -n '3p' /data/venus/installer-version 2>/dev/null)"

if [ ${installer_version:-0} -ge 20240718000000 ]; then
    exit 0
else
    exit 1
fi

