#!/bin/sh

if [ "$1" = "-h" ]; then
	echo "usage: $0"
	echo
	echo "Simple helper to set a password back to how it was after it left the factory"
	echo "if there is currently none set. If it left the factory without a default password,"
	echo "this script does nothing, since there is no default password already. If it left"
	echo "the factory with the BlueTooth PIN code as password that will be restored"
	echo
	echo "The intended usage is that after running a factory default script, i.o.w removing"
	echo "most of /data, this script will be called to restore the default password to"
	echo "factory default. Which migh be the PIN code or none at all."
fi

if [ ! -f /data/conf/vncpassword.txt ] && ve-is-password-set-by-default; then
    ve-set-passwd-to-pincode
fi

