#!/bin/sh

allow_default=0

usage() {
    echo "usage: $0"
    echo
    echo "Set the default password to the BlueTooth pincode as read from the EEPROM."
    echo
    echo "-h --help: this help"
    echo "--allow-default: Assume a default 000000 pincode if reading from the EEPROM failed."
    echo
    echo "Victron Energy B.V."
}

while [ "$#" -ne 0 ]; do
	case $1 in
	-h|--help)
        usage "$0"
        exit
	    ;;
	--allow-default)
        allow_default=1
	    ;;
	*)
		usage "$0"
		exit 1
	esac

	shift
done

pin="$(/opt/victronenergy/venus-eeprom/eeprom --show bluetooth-pin 2>/dev/null)"
if [ "$pin" = "" ]; then
    if [ "$allow_default" -eq 0 ]; then
        echo 'Error: could not read bluetooth pincode, giving up. See --allow-default.' >&2
        exit 1
    fi
    echo "Could not read pincode, using default instead."
    pin="000000"
fi

ve-set-passwd "$pin"
exit $?

