#!/bin/sh

set -e

ubiformat  /dev/mtd12
ubiattach /dev/ubi_ctrl -m 12

ubimkvol /dev/ubi0 -N rootfs1 -s 200MiB
ubimkvol /dev/ubi0 -N rootfs2 -s 200MiB
ubimkvol /dev/ubi0 -N data -s 32MiB

swupdate -v -b "0 1 2 3 4 5 6 7 8 9 10 11" -e "stable,copy1" -d https://updates.victronenergy.com/feeds/ccgx2/venus-swu-ccgx.swu

reboot
