#!/bin/sh

. /lib/venus/install.sh

SWUDEV=mmcblk0p1
MMCDEV=mmcblk1
ROOT_SIZE=
BOARD_ID_DEV=0-00500
TESTMODE_TTYS="ttyS2"

if [ -e /dev/lcd ]; then
    TTYS="$TTYS lcd"

    clearlcd() {
        printf '\f' >/dev/lcd
    }

    HOOK_msg=clearlcd

    # initialise LCD
    printf '\f\e[Lb\e[Lc\e[LD\e[L+' >/dev/lcd
fi

do_install
