#!/bin/sh

. /lib/venus/install.sh

SWUDEV=mmcblk0p1
MMCDEV=mmcblk1
ROOT_SIZE=2048
DATA_SIZE=2048
TTYS="$TTYS lcd"

clearlcd() {
    printf '\f' >/dev/lcd
}

HOOK_msg=clearlcd

# initialise LCD
printf '\f\e[Lb\e[Lc\e[LD\e[L+' >/dev/lcd

do_install
