#!/bin/sh

### BEGIN INIT INFO
# Provides:          hiawatha httpd httpd-cgi
# Required-Start:    $syslog $network $remote_fs
# Required-Stop:     $syslog $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Hiawatha webserver
# Description:       Hiawatha, a secure and advanced webserver.
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=sed_sbin_path/hiawatha
NAME=hiawatha
DESC="Hiawatha Web Server"
OPTS=""

WWW_BASE=/var/www/venus
OVERRIDE_BASE=/data/www

install_overrides() {
	mkdir -p /run/www

	for d in $(ls $WWW_BASE/default); do
		if [ -d $OVERRIDE_BASE/$d ]; then
			ln -sf $OVERRIDE_BASE/$d /run/www/
		else
			ln -sf $WWW_BASE/default/$d /run/www/
		fi
	done
}

case "$1" in
  start)
	echo -n "Starting $DESC: "
	mkdir -p /var/log/hiawatha &> /dev/null
	install_overrides
	start-stop-daemon --start -x "$DAEMON" -- $OPTS
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop -x "$DAEMON"
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop -x "$DAEMON"
	sleep 1
	start-stop-daemon --start -x "$DAEMON" -- $OPTS
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
