#! /bin/sh

case "$1" in
  start)
	modprobe fbcon
  ;;
  stop)
  ;;
  reload)
  ;;
  status)
  ;;
  restart|force-reload)
        $0 stop
        $0 start
  ;;
  *)
        echo "Usage: {start|stop|restart|reload|force-reload|status}"
        exit 1
  ;;
esac

exit 0
