#! /bin/sh

get_setting() {
    dbus-send --print-reply=literal --system --type=method_call \
              --dest=com.victronenergy.settings $1 \
              com.victronenergy.BusItem.GetValue |
        awk '/int32/ { print $3 }'
}

bridge_conf=/data/conf/mosquitto.d/vrm_bridge.conf
bridge_link=/run/mosquitto/vrm_bridge.conf

if [ "$(get_setting /Settings/Services/MqttVrm)" = 1 ]; then
    ln -sf $bridge_conf $bridge_link
else
    rm -f $bridge_link
fi

keydir=/data/keys
cert=$keydir/mosquitto.crt
key=$keydir/mosquitto.key

mkdir -m 700 -p $keydir

if ! openssl rsa -check -noout -in $key ||
   ! openssl verify -CAfile $cert $cert; then
    openssl req -subj /CN=venus.local -newkey rsa:2048 -nodes \
            -keyout $key -x509 -out $cert
fi

exec softlimit -d 100000000 -s 1000000 -a 100000000 \
     /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
