#! /bin/sh

keydir=/data/keys
cert=$keydir/mosquitto.crt
key=$keydir/mosquitto.key

mkdir -m 700 -p $keydir

if ! openssl rsa -check -noout -in $key ||
   ! openssl verify -CAfile $cert $cert; then
    openssl req -subj /CN=venus.local -newkey rsa:2048 -nodes \
            -keyout $key -x509 -out $cert
fi

exec softlimit -d 100000000 -s 1000000 -a 100000000 \
     /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
