#!/bin/sh

. /lib/venus/install.sh

SWUDEV=mmcblk0p1
MMCDEV=mmcblk1

LED_0=heartbeat
LED_1=mmc0
LED_2=usr2
LED_3=usr3

setleds() {
    while [ $# -ge 2 ]; do
        eval echo $2 \>/sys/class/leds/beaglebone:green:\$LED_$1/trigger
        shift 2
    done
}

capeled() {
    if [ $1 = "green" ]; then
        echo $2 > /sys/class/leds/vecape:green:ve0/trigger
        echo none > /sys/class/leds/vecape:red:ve1/trigger
    else
        echo none > /sys/class/leds/vecape:green:ve0/trigger
        echo $2 > /sys/class/leds/vecape:red:ve1/trigger
    fi
}

testmode() {
    stty -F /dev/ttyO2 115200
    TTYS="$TTYS ttyO2"
}

HOOK_error="capeled red default-on"
HOOK_testmode="testmode"
HOOK_format="setleds 0 timer; capeled red timer"
HOOK_rootfs1="setleds 0 default-on 1 timer"
HOOK_rootfs2="setleds 1 default-on 2 timer"
HOOK_bootloader="setleds 2 default-on 3 timer"
HOOK_cleanup="setleds 3 default-on; capeled green default-on"

do_mounts

setleds 0 none 1 none 2 none 3 none
capeled green none

# unlock u-boot environment
echo 0 >/sys/block/mmcblk1boot1/force_ro

do_install
