#!/bin/sh

USER=simple-upnpd
PROGRAM=/bin/simple-upnpd
PARAMS="--xml /etc/simple-upnpd.xml"

start_it()
{
	echo "Starting simple-upnpd"

	if [[ ! -e /etc/simple-upnpd.xml ]]
	then
		hwaddr=$(ifconfig -a | grep "eth0.*HWaddr" | awk '{print $(NF)}')
		hwaddr_small=$(echo ${hwaddr} | sed "s/://g" |  tr '[:upper:]' '[:lower:]' )
		cat /etc/simple-upnpd.skeleton.xml | sed -e "s/:::MAC:::/${hwaddr}/g" -e "s/:::mac_small:::/${hwaddr_small}/g"  > /etc/simple-upnpd.xml
	fi

	start-stop-daemon --start --quiet --user $USER --chuid $USER --exec $PROGRAM -- $PARAMS
}

stop_it()
{
	echo "Stopping simple-upnpd"
	start-stop-daemon --stop  --quiet --user $USER
}

case "$1" in
	start)
		start_it
	;;
	stop)
		stop_it
    ;;
	restart)
		stop_it
		sleep 1
		start_it
	;;
	*)
		echo "Usage: /etc/init.d/simple-upnpd {start|stop}"
		exit 1
	;;
esac

exit 0
