#!/bin/sh

if [[ ! -e /etc/simple-upnpd.xml ]]; then
	unique=$(cat /data/venus/unique-id)
	UNIQUE=$(echo ${unique} | tr '[:lower:]' '[:upper:]' | sed -e 's/.\{2\}/&:/g' -e 's/:$//g')
	name="$(installation-name)"
	sed -e "s/:::UNIQUE:::/${UNIQUE}/g" -e "s/:::unique:::/${unique}/g" -e "s/:::name:::/${name}/g" /etc/simple-upnpd.skeleton.xml > /etc/simple-upnpd.xml.tmp
	mv /etc/simple-upnpd.xml.tmp /etc/simple-upnpd.xml
fi

setuidgid simple-upnpd softlimit -d 100000000 -s 1000000 -a 100000000 /bin/simple-upnpd --xml /etc/simple-upnpd.xml -d
