#!/bin/sh

if [ ! -d /data/themes/overlay ]; then
	mkdir -p /data/themes/overlay
fi
chown -R php-fpm:php-fpm /data/themes/overlay

if [ ! -d /data/var/venus-www-sessions ]; then
	mkdir -p /data/var/venus-www-sessions
fi
chown -R php-fpm:php-fpm /data/var/venus-www-sessions
