MAINMACHINE := "${MACHINE}"
MACHINE:append = "-k3r5"

# Deploy to same location as main machine
DEPLOY_DIR_IMAGE:k3r5 = "${DEPLOY_DIR}/images/${MAINMACHINE}"

# Separate from main machine
TMPDIR:append = "-k3r5"

# Clashes with main machine otherwise
LICENSE_DIRECTORY:append = "-k3r5"
