# NOTE: meta-ti use ${MACHINE} here and enables a multiconfig setup from their
# machine config. That works for a single machine since that machine is then
# the default config. It won't work when building multiple machines in a
# multiconfig setup, since only one of them becomes the default config, which
# might not even have a k3r5.
#
# It would require a more fine grained control of the dependencies of machines.
# Since there is only one soc supported at the momeent, just use the intended
# machine name, not that flexible, but should at least work.
MAINMACHINE := "am62xx"
MACHINE = "am62xx-k3r5"

# Deploy to same location as main machine
DEPLOY_DIR_IMAGE:k3r5 = "${DEPLOY_DIR}/images/${MAINMACHINE}"

# Separate from main machine
TMPDIR:append = "-k3r5"

# Clashes with main machine otherwise
LICENSE_DIRECTORY:append = "-k3r5"
