SOC_FAMILY = "k3r5"

require conf/machine/include/soc-family.inc
require conf/machine/include/arm/armv7r/tune-cortexr5.inc

UBOOT_MACHINE = "am62x_victron_r5_config"
UBOOT_IMAGE = "tiboot3.bin"

NO_RECOMMENDATIONS = "1"
