SOC_FAMILY = "k3"

require conf/machine/include/soc-family.inc
require conf/machine/include/arm/armv8a/tune-cortexa53.inc

BBMULTICONFIG += "k3r5"

MACHINE_FEATURES = "usbhost vfat rtc serial wifi"

# start-gui can switch between gui-v1 and gui-v2
START_GUI = "start-gui"

PREFERRED_PROVIDER_virtual/kernel = "linux-venus"
PREFERRED_PROVIDER_virtual/bootloader = "u-boot-k3"
PREFERRED_VERSION_u-boot-fw-utils = "2025.01-k3%"

IMAGE_FSTYPES = "ext4.gz"
ROOT_FSTYPE = "ext4.gz"

FSTAB = "mmc0"

UBOOT_MACHINE = "am62x_victron_a53_config"
UBOOT_IMAGE = "u-boot.img"
SPL_BINARY = "tispl.bin"

KERNEL_CONFIG = "k3_victron_defconfig"
KERNEL_IMAGETYPE = "Image"
KERNEL_DEVICETREE = "\
    ti/k3-am625-cerbo-b10.dtb \
    ti/k3-am625-cerbo-b11.dtb \
"
KERNEL_PACKAGES = "kernel-image kernel-modules"

BOARD_IDS = "\
    cerbogx_b10:VCBA \
    cerbogx_b11:VCBB \
"

IMAGE_BOOT_FILES = "tiboot3.bin ${SPL_BINARY} ${UBOOT_IMAGE}"
SWU_EXTRA_IMAGES = "${IMAGE_BOOT_FILES}"

INITTAB = "S0:12345:respawn:/sbin/getty -L -l /sbin/autologin -n 115200 ttyS0 vt102"
USE_VT = "0"

VENUS_WLAN_AP = "1"
