#! /bin/sh

subsys=$(basename $(readlink /sys/class/net/$INTERFACE/../../subsystem))

case $subsys in
    usb)
        # The built-in USB wifi device provides two interfaces.  The MAC
        # addresses of the interfaces differ in the value of the locally
        # administered bit.  The interface with this bit set becomes the
        # the access point, the other is unused.

        addr1=$(cut -d: -f1 /sys/class/net/$INTERFACE/address)
        local=$((0x$addr1 & 2))

        if [ $local -gt 0 ]; then
            echo ap0
        else
            echo disabled-$INTERFACE
        fi

        ;;

    sdio)
        # The SDIO wifi is used unless an external adapter is attached,
        # as indicated by the presence of more than 3 wlan devices.

        if [ $(ls /sys/class/net | grep -Ec 'wlan|^ap') -gt 3 ]; then
            echo disabled-wifi0
        else
            echo wifi0
        fi
        ;;
esac
