#!/bin/sh

set -e

ubiformat  /dev/mtd12
ubiattach /dev/ubi_ctrl -m 12

ubimkvol /dev/ubi0 -N rootfs1 -s 200MiB
ubimkvol /dev/ubi0 -N rootfs2 -s 200MiB
ubimkvol /dev/ubi0 -N data -s 32MiB

mount /dev/mmcblk0p1 /mnt/card
swupdate -v -b "0 1 2 3 4 5 6 7 8 9 10 11" -e "stable,copy1" -i /mnt/card/venus.swu
swupdate -v -b "0 1 2 3 4 5 6 7 8 9 10 11" -e "stable,copy2" -i /mnt/card/venus.swu
swupdate -v -b "0 1 2 3 4 5 6 7 8 9 10 11" -e "stable,bootloader" -i /mnt/card/venus.swu
