#!/bin/sh

. /lib/venus/install.sh

SWUDEV="mmcblk0p1 sda1 mmcblk0 sda"
UBIPART=12
MODULES="fbcon"
TTYS="$TTYS tty0"

postinst() {
    msg "updating boot instructions..."
    fw_setenv -s /usr/share/u-boot/u-boot.env
}

HOOK_postinst=postinst

do_install
