#! /bin/sh

HCI=$1

random_addr() {
    dd if=/dev/urandom bs=6 count=1 | hexdump -e '6/1 "%d " "\n"' | (
        read a b
        set -- $(printf '%02x ' $((a|0xc0)) $b)
        IFS=:
        echo "$*"
    )
}

ADDR_STORE=/data/venus/bluetooth-addr

get_addr() {
    dev=$1
    addr=$(awk "\$1 == \"$dev\" { print \$2 }" $ADDR_STORE)

    if [ -z "$addr" ]; then
        addr=$(random_addr)
        echo $dev $addr >>$ADDR_STORE
    fi

    echo $addr
}

init_wait=0
while hciconfig $HCI | grep -qw INIT; do
    if [ "$init_wait" -ge 50 ]; then
        logger -t bt-config "$HCI remained in INIT state; skipping configuration"
        exit 1
    fi

    init_wait=$((init_wait + 1))
    usleep 200000
done

if hciconfig $HCI | grep -qw RAW; then
    yes | btmgmt -i $HCI public-addr $(get_addr $HCI)
    usleep 200000
fi

# btmgmt can hang when started by udev. Piping with yes prevents that.
yes | btmgmt -i $HCI le on
yes | btmgmt -i $HCI bredr off

# start services, or restart them if already running
services_up="/service/vesmart-server"
# only restart these
services_restart="$services_up /service/dbus-ble-sensors"

svc -t $services_restart
svc -u $services_up
