#! /bin/sh

dev=/sys/$1
con=$2
bus=$3

card=$(basename $dev)
disp=$dev/$card-$con
stat=$(cat $disp/status)

get_devices() (
    cd /sys/bus/i2c/devices/$1
    ls -d ${1#*-}-*
)

connected() {
    for d in $(get_devices $bus); do
        echo $d >/sys/bus/i2c/drivers_probe
    done

    edid_size=$(wc -c $disp/edid | cut -d' ' -f1)

    if [ $edid_size -lt 128 ]; then
        # Bad EDID, use resolution of GX Touch 50
        mode=800x480
    else
        mode=$(head -n1 $disp/modes)
    fi

    fbset -xres ${mode%x*} -yres ${mode#*x}
    cat /dev/zero >/dev/fb0
}

disconnected() {
    for d in $(get_devices $bus); do
        echo $d >/sys/bus/i2c/devices/$d/driver/unbind
    done
}

case $stat in
    connected|disconnected)
        $stat
        svc -t /service/gui
        ;;
    *)
        logger "Unknown display status: $stat"
        ;;
esac
