#! /bin/sh

rename_if() {
    ip link set $1 down
    ip link set $1 name $2
}

case $ACTION in
    add)
        # disable built-in interface if this is the first external one
        if ls /sys/class/net | grep -q ^wifi0; then
            rename_if wifi0 disabled-wifi0
        fi
        ;;
    remove)
        # enable built-in interface if this was the last external one
        if ! ls /sys/class/net | grep -q ^wlan; then
            rename_if disabled-wifi0 wifi0
        fi
        ;;
esac

# connman needs to be restarted for device blacklist to work
killall connmand
