#! /bin/sh

# The built-in wifi device provides two interfaces.  We want to use
# one in normal station mode and the other as access point.  The MAC
# addresses of the interfaces differ in the value of the locally
# administered bit.  The interface with this bit unset becomes the
# station, the other the access point.
#
# Additionally, if an external wifi adapter is attached, the built-in
# one will not be used as station.  This condition is detected by
# counting the number of wlan* interfaces present.  Since the AP may
# or may not have been renamed before this check, also include this
# name and look for a total greater than 2.

addr1=$(cut -d: -f1 /sys/class/net/$INTERFACE/address)
local=$((0x$addr1 & 2))

if [ $local -gt 0 ]; then
    echo ap0
elif [ $(ls /sys/class/net | grep -Ec '^(wlan|ap0)') -gt 2 ]; then
    echo disabled-wifi0
else
    echo wifi0
fi
