#! /bin/sh

cmd=$1
shift

do_ipt() {
    cmd=$1
    opt=$2
    shift 2

    case $opt in
        -A)
            $cmd -C "$@" 2>/dev/null && return
            $cmd -A "$@"
            ;;
        -D)
            while $cmd -D "$@" 2>/dev/null; do true; done
            ;;
    esac
}

apply() {
    do_ipt iptables  "$@"
    do_ipt ip6tables "$@"
}

rules() {
    allow=$1
    deny=$2
    proto=$3
    port=$4

    match="-p $proto --dport $port"

    apply $allow new-conn $match -j ACCEPT
    apply $deny  new-conn $match -j REJECT
}

allow() {
    rules -A -D "$@"
}

deny() {
    rules -D -A "$@"
}

case "$cmd" in
    allow|deny)
        $cmd "$@"
        ;;
    *)
        echo "Unknown action $cmd"
        exit 1
        ;;
esac
